# Generated by Django 6.0.3 on 2026-03-11 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100, unique=True, verbose_name='Case number')),
                ('case_type', models.CharField(choices=[('CIVIL', 'Civil'), ('CRIMINAL', 'Criminal'), ('WRIT', 'Writ'), ('APPEAL', 'Appeal'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20, verbose_name='Case type')),
                ('case_title', models.CharField(max_length=500, verbose_name='Case title')),
                ('petitioner_name', models.CharField(max_length=300, verbose_name='Petitioner name')),
                ('respondent_name', models.CharField(max_length=300, verbose_name='Respondent name')),
                ('filed_date', models.DateField(verbose_name='Filed date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ADMITTED', 'Admitted'), ('DISPOSED', 'Disposed'), ('TRANSFERRED', 'Transferred'), ('MISC', 'Miscellaneous')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('bench', models.CharField(blank=True, max_length=200, verbose_name='Bench')),
                ('judge_name', models.CharField(blank=True, max_length=200, verbose_name='Judge name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-filed_date', 'case_number'],
                'indexes': [models.Index(fields=['case_type'], name='idx_case_type'), models.Index(fields=['status', 'case_type'], name='idx_status_case_type')],
            },
        ),
    ]
