# Generated by Django 6.0.3 on 2026-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='idx_case_type',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='idx_status_case_type',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
