# Generated by Django 6.0.3 on 2026-03-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CISDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(help_text='e.g., FILING_NUMBER_GENERATION, DATA_SYNC', max_length=100, verbose_name='Operation type')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20, verbose_name='Status')),
                ('source_case_id', models.CharField(max_length=100, verbose_name='Source case ID (from CMS)')),
                ('target_case_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Target case number (from CIS)')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload sent')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Response received')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'CIS Data Log',
                'verbose_name_plural': 'CIS Data Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CISFilingNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='e.g., EC_SKNM01/2026/12345', max_length=100, unique=True, verbose_name='Case number (CIS filing number)')),
                ('case_title', models.CharField(max_length=500, verbose_name='Case title from CIS')),
                ('case_type', models.CharField(max_length=50, verbose_name='Case type from CIS')),
                ('petitioner', models.CharField(max_length=300, verbose_name='Petitioner name from CIS')),
                ('respondent', models.CharField(max_length=300, verbose_name='Respondent name from CIS')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='Filing date in CIS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'CIS Filing Number',
                'verbose_name_plural': 'CIS Filing Numbers',
                'ordering': ['-created_at'],
            },
        ),
    ]
