# Generated by Django 6.0.3 on 2026-03-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CISDataLog',
        ),
        migrations.DeleteModel(
            name='CISFilingNumber',
        ),
    ]
