# Generated by Django 6.0.3 on 2026-03-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('application', models.CharField(blank=True, max_length=120, null=True)),
                ('txn_id', models.CharField(blank=True, max_length=120, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('callback_method', models.CharField(blank=True, max_length=10, null=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('redirect_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transaction',
                'ordering': ['-created_at'],
            },
        ),
    ]
