# Generated by Django 6.0.3 on 2026-04-02 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfilingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('advocate', 'Advocate'), ('scrutiny_officer', 'Scrutiny Officer')], db_index=True, max_length=32)),
                ('notification_type', models.CharField(choices=[('filing_submitted', 'Filing Submitted'), ('documents_uploaded', 'Documents Uploaded'), ('ia_filed', 'IA Filed'), ('scrutiny_accepted', 'Scrutiny Accepted'), ('scrutiny_rejected', 'Scrutiny Rejected'), ('scrutiny_partial', 'Scrutiny Partially Rejected')], max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('e_filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.efiling')),
                ('ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.ia')),
            ],
            options={
                'db_table': 'efiling_notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
