# Generated by Django 4.2.29 on 2026-03-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfilingNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'efiling_number_sequence',
            },
        ),
    ]
