# Generated by Django 6.0.3 on 2026-03-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efiling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EfilingNumberSequence',
        ),
    ]
