# Generated by Django 6.0.3 on 2026-04-20 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_efiling_has_payment_objection_and_more'),
        ('efiling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_fee_amount', models.DecimalField(decimal_places=2, help_text='The correct court fee amount as determined by the scrutiny officer', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks explaining the payment objection', null=True)),
                ('raised_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the objection was resolved', null=True)),
                ('resolved_by_payment_id', models.CharField(blank=True, help_text='The payment transaction ID that resolved this objection', max_length=100, null=True)),
                ('e_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_objections', to='core.efiling')),
                ('raised_by', models.ForeignKey(blank=True, help_text='The scrutiny officer who raised the objection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_payment_objections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'efiling_payment_objection',
                'ordering': ['-raised_at'],
            },
        ),
    ]
