# Generated by Django 6.0.3 on 2026-04-17 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efiling', '0002_paymentobjection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentobjection',
            name='raised_by',
            field=models.ForeignKey(blank=True, help_text='The scrutiny officer who raised the objection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_payment_objections', to=settings.AUTH_USER_MODEL),
        ),
    ]
