# Generated by Django 6.0.3 on 2026-04-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efiling', '0003_alter_paymentobjection_raised_by'),
        ('efiling', '0003_paymentobjection_resolved_by_payment_id'),
    ]

    operations = [
    ]
