# Generated by Django 6.0.3 on 2026-03-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0032_merge_20260323_1041"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CauseList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("cause_list_date", models.DateField()),
                ("bench_key", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cause_lists_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="media/causelists/",
                        max_length=512,
                    ),
                ),
            ],
            options={
                "db_table": "cause_list",
            },
        ),
        migrations.CreateModel(
            name="CauseListEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "serial_no",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("included", models.BooleanField(default=True)),
                (
                    "cause_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="listing.CauseList",
                    ),
                ),
                (
                    "efiling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cause_list_entries",
                        to="core.efiling",
                    ),
                ),
            ],
            options={
                "db_table": "cause_list_entry",
            },
        ),
        migrations.AlterUniqueTogether(
            name="causelist",
            unique_together={("cause_list_date", "bench_key")},
        ),
        migrations.AlterUniqueTogether(
            name="causelistentry",
            unique_together={("cause_list", "efiling")},
        ),
        migrations.AddIndex(
            model_name="causelistentry",
            index=models.Index(fields=["cause_list", "included"], name="cause_list_included_idx"),
        ),
    ]

