# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="causelist",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                max_length=512,
                null=True,
                upload_to="causelists/",
            ),
        ),
    ]

