# Generated by Django 6.0.3 on 2026-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='causelistentry',
            name='petitioner_advocate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='causelistentry',
            name='respondent_advocate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
