# Generated by Django 6.0.3 on 2026-03-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_causelist_pdf_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='causelistentry',
            new_name='cause_list__cause_l_cf21e9_idx',
            old_name='cause_list_included_idx',
        ),
    ]
