# Generated by Django 6.0.3 on 2026-04-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_causelistentry_petitioner_advocate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='causelistentry',
            name='selected_ias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
