# Generated by Django 6.0.3 on 2026-04-12 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_causelistentry_selected_ias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='causelist',
            index=models.Index(fields=['cause_list_date', 'status'], name='cause_list_cause_l_251fe0_idx'),
        ),
    ]
