# Generated by Django 6.0.3 on 2026-03-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetypet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
    ]
