# Generated by Django 6.0.3 on 2026-04-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documentindex_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetypet',
            name='reg_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetypet',
            name='reg_year',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentindex',
            name='sequence_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
