# Generated by Django 6.0.3 on 2026-03-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_casetypet_created_by_casetypet_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='efiliingacts',
            table='e_filing_acts',
        ),
        migrations.AlterModelTable(
            name='efiling',
            table='e_filing',
        ),
        migrations.AlterModelTable(
            name='efilingcasedetails',
            table='e_filing_case_details',
        ),
        migrations.AlterModelTable(
            name='efilinglitigant',
            table='e_filing_litigant',
        ),
    ]
