# Generated by Django 6.0.3 on 2026-03-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_efilingacts_table_alter_efiling_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cisfilingnumber',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cisfilingnumber',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CISDataLog',
        ),
        migrations.DeleteModel(
            name='CISFilingNumber',
        ),
    ]
