# Generated by Django 6.0.3 on 2026-04-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_casetypet_reg_no_casetypet_reg_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efiling',
            name='filing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efiling',
            name='petitioner_vs_respondent',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
