# Generated by Django 6.0.3 on 2026-04-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_efiling_filing_date_efiling_petitioner_vs_respondent'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocuments',
            name='filed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
