# Generated by Django 6.0.3 on 2026-03-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_efiling_is_draft_alter_efilingacts_e_filing_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfilingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'e_filing_sequence',
            },
        ),
    ]
