# Generated by Django 6.0.3 on 2026-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_efilingsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efiling',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
