# Generated by Django 6.0.3 on 2026-03-16 09:31

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_efiling_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocuments',
            name='is_ia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efilingdocuments',
            name='parent_e_filing_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_documents', to='core.efilingdocuments'),
        ),
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='document_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='efilingdocumentsindex',
            name='file_part_path',
            field=models.FileField(max_length=512, upload_to=apps.core.models.EfilingDocumentsIndex.file_part_upload_to),
        ),
        migrations.CreateModel(
            name='IA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('e_filing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ia_text', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('e_filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ias', to='core.efiling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
