# Generated by Django 6.0.3 on 2026-03-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_efilingdocuments_is_ia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilt',
            name='court_no',
        ),
        migrations.RemoveField(
            model_name='civilt',
            name='date_first_list',
        ),
        migrations.RemoveField(
            model_name='civilt',
            name='date_next_list',
        ),
        migrations.RemoveField(
            model_name='civilt',
            name='date_of_filing',
        ),
        migrations.RemoveField(
            model_name='civilt',
            name='res_sex',
        ),
        migrations.RemoveField(
            model_name='civilt',
            name='time_of_filing',
        ),
        migrations.AlterField(
            model_name='actt',
            name='lactname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='civilt',
            name='lpet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilt',
            name='lres_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilt',
            name='pet_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='civilt',
            name='res_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
