# Generated by Django 6.0.3 on 2026-03-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_civilt_court_no_remove_civilt_date_first_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='court_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
