# Generated by Django 6.0.3 on 2026-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_court_court_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='efilingdocuments',
            table='efiling_documents',
        ),
        migrations.AlterModelTable(
            name='efilingdocumentsindex',
            table='efiling_documents_index',
        ),
        migrations.AlterModelTable(
            name='ia',
            table='ia',
        ),
    ]
