# Generated by Django 6.0.3 on 2026-03-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_efilingdocuments_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilinglitigant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litigants', to='core.orgnamet'),
        ),
        migrations.AddField(
            model_name='efilinglitigant',
            name='sequence_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
