# Generated by Django 6.0.3 on 2026-04-15 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_efiling_documents_index_scrutiny_columns_if_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purpose_code', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('purpose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lpurpose_name', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_flag', models.SmallIntegerField(blank=True, null=True)),
                ('display', models.TextField()),
                ('purpose_priority', models.SmallIntegerField()),
                ('res_disp', models.SmallIntegerField()),
                ('national_code', models.BigIntegerField()),
                ('substage_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('amd', models.CharField(blank=True, max_length=1, null=True)),
                ('create_modify', models.DateTimeField(blank=True, null=True)),
                ('est_code_src', models.CharField(max_length=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purpose_t',
            },
        ),
    ]
