# Generated by Django 6.0.3 on 2026-04-16 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_case_access_request'),
        ('core', '0014_purposet'),
    ]

    operations = [
    ]
