# Generated by Django 6.0.3 on 2026-03-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_efiling_accepted_at_efiling_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocuments',
            name='final_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='efile/final_documents/'),
        ),
    ]
