<<<<<<< HEAD
# Generated by Django 6.0.3 on 2026-04-16 07:03

=======
>>>>>>> fc1a630956f2185b28559fad92417cfad62b239b
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('core', '0014_case_access_request'),
        ('core', '0014_purposet'),
    ]

    operations = [
    ]
=======
        ("core", "0014_case_access_request"),
        ("core", "0014_purposet"),
    ]

    operations = []
>>>>>>> fc1a630956f2185b28559fad92417cfad62b239b
