# Generated by Django 4.2.29 on 2026-03-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_efiling_accepted_at_efiling_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocuments',
            name='ia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.ia'),
        ),
    ]
