# Generated by Django 6.0.3 on 2026-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0014_case_access_request_0014_purposet'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetypet',
            name='annexure_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
