# Generated by Django 6.0.4 on 2026-04-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_0014_case_access_request_0014_purposet'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsA',
            fields=[
                ('pk', models.CompositePrimaryKey('order_no', 'cino', blank=True, editable=False, primary_key=True, serialize=False)),
                ('case_no', models.CharField(blank=True, max_length=15, null=True)),
                ('order_no', models.SmallIntegerField()),
                ('order_dt', models.DateField(blank=True, null=True)),
                ('download', models.TextField()),
                ('upload', models.TextField()),
                ('doc_type', models.SmallIntegerField()),
                ('ordloc_lang', models.TextField()),
                ('judgedecree', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('oldorder_dt', models.DateField(blank=True, null=True)),
                ('userlogin', models.CharField(blank=True, max_length=150, null=True)),
                ('jocode', models.CharField(blank=True, max_length=150, null=True)),
                ('modify_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('disp_nature', models.SmallIntegerField()),
                ('hashkey', models.CharField(blank=True, max_length=200, null=True)),
                ('court_no', models.IntegerField()),
                ('cino', models.CharField(max_length=16)),
                ('reportable_judgement', models.CharField(blank=True, max_length=1, null=True)),
                ('filing_no', models.CharField(blank=True, max_length=15, null=True)),
                ('amd', models.CharField(blank=True, max_length=1, null=True)),
                ('create_modify', models.DateTimeField(blank=True, null=True)),
                ('ia_no', models.CharField(blank=True, max_length=12, null=True)),
                ('ia_case_type', models.IntegerField(blank=True, null=True)),
                ('auther_judge', models.IntegerField(blank=True, null=True)),
                ('comm_judge', models.IntegerField(blank=True, null=True)),
                ('appeal_status', models.IntegerField(blank=True, null=True)),
                ('headnote', models.TextField(blank=True, null=True)),
                ('acts', models.TextField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('judge_code', models.CharField(blank=True, max_length=50, null=True)),
                ('desig_code', models.CharField(blank=True, max_length=50, null=True)),
                ('nc_court', models.CharField(blank=True, max_length=9, null=True)),
                ('nc_no', models.IntegerField(blank=True, null=True)),
                ('nc_year', models.IntegerField(blank=True, null=True)),
                ('nc', models.CharField(blank=True, max_length=25, null=True)),
                ('benchtype', models.CharField(blank=True, max_length=2, null=True)),
                ('judgment', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'order_details_a',
                'managed': False,
            },
        ),
    ]
