# Generated by Django 4.2.29 on 2026-03-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_efilingdocuments_ia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efilingdocuments',
            name='ia',
        ),
    ]
