# Generated by Django 6.0.4 on 2026-04-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_orderdetailsa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailsa',
            options={},
        ),
    ]
