# Generated by Django 4.2.29 on 2026-03-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_efilingdocuments_final_document'),
        ('core', '0016_remove_efilingdocuments_ia'),
    ]

    operations = [
    ]
