# Generated by Django 4.2.29 on 2026-03-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20260317_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efilingdocumentsscrutinyhistory',
            name='document_index',
        ),
        migrations.AddField(
            model_name='efilingdocumentsscrutinyhistory',
            name='efiling_document_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrutiny_history', to='core.efilingdocumentsindex'),
        ),
    ]
