# Generated by Django 6.0.4 on 2026-04-17 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_orderdetailsa_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS order_details_a (
                    case_no varchar(15) NULL,
                    order_no smallint NOT NULL,
                    order_dt date NULL,
                    download text NOT NULL,
                    upload text NOT NULL,
                    doc_type smallint NOT NULL,
                    ordloc_lang text NOT NULL,
                    judgedecree integer NULL,
                    "timestamp" timestamp with time zone NOT NULL,
                    oldorder_dt date NULL,
                    userlogin varchar(150) NULL,
                    jocode varchar(150) NULL,
                    modify_flag varchar(1) NULL,
                    disp_nature smallint NOT NULL,
                    hashkey varchar(200) NULL,
                    court_no integer NOT NULL,
                    cino varchar(16) NOT NULL,
                    reportable_judgement varchar(1) NULL,
                    filing_no varchar(15) NULL,
                    amd varchar(1) NULL,
                    create_modify timestamp with time zone NULL,
                    ia_no varchar(12) NULL,
                    ia_case_type integer NULL,
                    auther_judge integer NULL,
                    comm_judge integer NULL,
                    appeal_status integer NULL,
                    headnote text NULL,
                    acts text NULL,
                    citation text NULL,
                    judge_code varchar(50) NULL,
                    desig_code varchar(50) NULL,
                    nc_court varchar(9) NULL,
                    nc_no integer NULL,
                    nc_year integer NULL,
                    nc varchar(25) NULL,
                    benchtype varchar(2) NULL,
                    judgment varchar(1) NULL,
                    PRIMARY KEY (order_no, cino)
                );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='orderdetailsa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetailsa',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetailsa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdetailsa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetailsa',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
