# Generated by Django 6.0.3 on 2026-03-17 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_efilingdocumentsscrutinyhistory_document_index_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentindex',
            table='document_index',
        ),
        migrations.AlterModelTable(
            name='efilingdocumentsscrutinyhistory',
            table='efiling_documents_scrutiny_history',
        ),
        migrations.AlterModelTable(
            name='filescrutinychecklist',
            table='file_scrutiny_checklist',
        ),
    ]
