# Generated by Django 6.0.4 on 2026-04-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_0017_efilingdocuments_0019_published_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efilingdocuments',
            name='document_filing_submitted_at',
        ),
    ]
