# Generated by Django 6.0.3 on 2026-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vakalatnama_efilerdocumentaccecss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakalatnama',
            name='vakalatnama_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='media/efile/vakalatnamas/'),
        ),
    ]
