# Generated by Django 6.0.3 on 2026-03-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_vakalatnama_vakalatnama_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vakalatnama',
            name='is_final',
        ),
    ]
