# Generated by Django 6.0.3 on 2026-04-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ensure_document_filing_submitted_at_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='efiling',
            name='has_payment_objection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efiling',
            name='objection_resolved_by_payment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efiling',
            name='payment_objection_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
