# Generated by Django 6.0.3 on 2026-03-18 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_vakalatnama_is_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EfilerDocumentAccecss',
            new_name='EfilerDocumentAccess',
        ),
    ]
