# Generated by Django 6.0.3 on 2026-03-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_efilerdocumentaccecss_efilerdocumentaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='is_new_for_scrutiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='last_resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='scrutiny_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_SCRUTINY', 'Under Scrutiny'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=32),
        ),
        migrations.AddField(
            model_name='efilingdocumentsscrutinyhistory',
            name='scrutiny_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_SCRUTINY', 'Under Scrutiny'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=32),
        ),
    ]
