# Generated by Django 6.0.3 on 2026-03-20 05:20

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_efilingdocumentsindex_is_new_for_scrutiny_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocateT',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('adv_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('adv_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ladv_name', models.CharField(blank=True, max_length=100, null=True)),
                ('adv_reg', models.CharField(blank=True, max_length=20, null=True)),
                ('display', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('laddress', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('adv_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('adv_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('adv_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('adv_phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('off_add', models.TextField(blank=True, null=True)),
                ('loff_add', models.TextField(blank=True, null=True)),
                ('dist_code', models.SmallIntegerField()),
                ('taluka_code', models.SmallIntegerField()),
                ('village_code', models.IntegerField()),
                ('village1_code', models.IntegerField()),
                ('village2_code', models.IntegerField()),
                ('town_code', models.IntegerField()),
                ('ward_code', models.IntegerField()),
                ('adv_fax', models.CharField(blank=True, max_length=15, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('debarred', models.TextField()),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('dist_code_res', models.SmallIntegerField()),
                ('taluka_code_res', models.SmallIntegerField()),
                ('village_code_res', models.IntegerField()),
                ('village1_code_res', models.IntegerField()),
                ('village2_code_res', models.IntegerField()),
                ('town_code_res', models.IntegerField()),
                ('ward_code_res', models.IntegerField()),
                ('status', models.IntegerField()),
                ('frequent', models.TextField()),
                ('adv_full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('adv_seniority', models.IntegerField(blank=True, null=True)),
                ('adv_gender', models.CharField(blank=True, max_length=1, null=True)),
                ('state_id_res', models.IntegerField(blank=True, null=True)),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('advocate_type', models.SmallIntegerField()),
                ('ori_adv_code', models.BigIntegerField(blank=True, null=True)),
                ('ori_adv_bar', models.CharField(blank=True, max_length=20, null=True)),
                ('adv_desig_from_date', models.DateField(blank=True, null=True)),
                ('amd', models.CharField(blank=True, max_length=1, null=True)),
                ('create_modify', models.DateTimeField(blank=True, null=True)),
                ('est_code_src', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'advocate_t',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='vakalatnama',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='efilingdocuments',
            name='final_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.core.models.EfilingDocuments.final_document_upload_to),
        ),
        migrations.AlterField(
            model_name='vakalatnama',
            name='vakalatnama_document',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='efile/vakalatnamas/'),
        ),
    ]
