# Generated by Django 6.0.3 on 2026-03-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_advocatet_vakalatnama_is_final_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advocatet',
            options={},
        ),
    ]
