# Generated by Django 6.0.3 on 2026-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_vakalatnama_is_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IAfilingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_sequence', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ia_filing_sequence',
            },
        ),
        migrations.AddField(
            model_name='efilingdocuments',
            name='ia_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
