# Generated by Django 6.0.3 on 2026-03-23 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_efilingdocumentsindex_draft_review_fields'),
        ('core', '0030_iafilingsequence_efilingdocuments_ia_number'),
    ]

    operations = [
    ]
