# Generated by Django 6.0.3 on 2026-03-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20260323_0437'),
        ('core', '0031_merge_20260323_1000'),
    ]

    operations = [
    ]
