# Generated by Django 6.0.3 on 2026-03-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_initial'),
        ('core', '0033_initial_models'),
    ]

    operations = [
    ]
