# Generated by Django 6.0.3 on 2026-04-01 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_merge_0033_initial_0033_initial_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderJudgeAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('reader_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_judge_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('judge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_assignment', to='core.judget')),
            ],
            options={
                'db_table': 'reader_judge_assignment',
            },
        ),
        migrations.AddIndex(
            model_name='readerjudgeassignment',
            index=models.Index(fields=['reader_user'], name='reader_judg_reader__8c2be2_idx'),
        ),
        migrations.AddIndex(
            model_name='readerjudgeassignment',
            index=models.Index(fields=['effective_from', 'effective_to'], name='reader_judg_effecti_fb4416_idx'),
        ),
    ]