# Generated by Django 6.0.3 on 2026-04-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_readerjudgeassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='readerjudgeassignment',
            new_name='reader_judg_reader__b0a408_idx',
            old_name='reader_judg_reader__8c2be2_idx',
        ),
        migrations.RenameIndex(
            model_name='readerjudgeassignment',
            new_name='reader_judg_effecti_33ff8d_idx',
            old_name='reader_judg_effecti_fb4416_idx',
        ),
    ]
