# Generated by Django 6.0.3 on 2026-04-01 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_reader_judg_reader__8c2be2_idx_reader_judg_reader__b0a408_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='efilingdocumentsindex',
            name='parent_document_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resubmissions', to='core.efilingdocumentsindex'),
        ),
    ]
