# Generated by Django 6.0.3 on 2026-04-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtroomJudgeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('forwarded_for_date', models.DateField()),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('REQUESTED_DOCS', 'Requested Documents')], default='DECLINED', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('reader_listing_remark', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_decisions', to='core.efiling')),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_decisions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_judge_decision',
            },
        ),
        migrations.CreateModel(
            name='CourtroomDecisionRequestedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling_document_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_requested_documents', to='core.efilingdocumentsindex')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('judge_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_documents', to='judge.courtroomjudgedecision')),
            ],
            options={
                'db_table': 'courtroom_decision_requested_document',
            },
        ),
        migrations.CreateModel(
            name='CourtroomDocumentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('annotation_text', models.TextField(blank=True, null=True)),
                ('annotation_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling_document_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_annotations', to='core.efilingdocumentsindex')),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_document_annotations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_document_annotation',
                'indexes': [models.Index(fields=['judge_user'], name='courtroom_d_judge_u_127da6_idx')],
                'unique_together': {('judge_user', 'efiling_document_index')},
            },
        ),
        migrations.AddIndex(
            model_name='courtroomjudgedecision',
            index=models.Index(fields=['listing_date', 'approved'], name='courtroom_j_listing_a6e07d_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomjudgedecision',
            index=models.Index(fields=['forwarded_for_date', 'approved'], name='courtroom_j_forward_c959f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtroomjudgedecision',
            unique_together={('judge_user', 'efiling', 'forwarded_for_date')},
        ),
        migrations.AddIndex(
            model_name='courtroomdecisionrequesteddocument',
            index=models.Index(fields=['judge_decision'], name='courtroom_d_judge_d_d60af1_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomdecisionrequesteddocument',
            index=models.Index(fields=['efiling_document_index'], name='courtroom_d_efiling_a616a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtroomdecisionrequesteddocument',
            unique_together={('judge_decision', 'efiling_document_index')},
        ),
    ]
