# Generated by Django 6.0.3 on 2026-03-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0033_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtroomForward",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("forwarded_for_date", models.DateField()),
                ("bench_key", models.CharField(max_length=50)),
                (
                    "forwarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courtroom_forwards_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "efiling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courtroom_forwards",
                        to="core.efiling",
                    ),
                ),
            ],
            options={
                "db_table": "courtroom_forward",
            },
        ),
        migrations.CreateModel(
            name="CourtroomJudgeDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("forwarded_for_date", models.DateField()),
                ("listing_date", models.DateField()),
                ("approved", models.BooleanField(default=False)),
                ("decision_notes", models.TextField(blank=True, null=True)),
                (
                    "efiling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courtroom_decisions",
                        to="core.efiling",
                    ),
                ),
                (
                    "judge_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courtroom_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courtroom_judge_decision",
            },
        ),
        migrations.AddIndex(
            model_name="courtroomjudgedecision",
            index=models.Index(fields=["listing_date", "approved"], name="courtroom_judge_decision_list_date_approved_idx"),
        ),
        migrations.AddIndex(
            model_name="courtroomjudgedecision",
            index=models.Index(fields=["forwarded_for_date", "approved"], name="courtroom_judge_decision_fwd_date_approved_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="courtroomjudgedecision",
            unique_together={("judge_user", "efiling", "forwarded_for_date")},
        ),
        migrations.CreateModel(
            name="CourtroomDocumentAnnotation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("annotation_text", models.TextField(blank=True, null=True)),
                (
                    "efiling_document_index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courtroom_annotations",
                        to="core.efilingdocumentsindex",
                    ),
                ),
                (
                    "judge_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courtroom_document_annotations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "courtroom_document_annotation",
            },
        ),
        migrations.AlterUniqueTogether(
            name="courtroomdocumentannotation",
            unique_together={("judge_user", "efiling_document_index")},
        ),
        migrations.AddIndex(
            model_name="courtroomdocumentannotation",
            index=models.Index(fields=["judge_user"], name="courtroom_doc_anno_judge_idx"),
        ),
        migrations.AddIndex(
            model_name="courtroomforward",
            index=models.Index(fields=["forwarded_for_date", "bench_key"], name="courtroom_forward_fwd_date_bench_idx"),
        ),
    ]

