# Generated by Django 6.0.3 on 2026-04-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('judge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtroomSharedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('document_index_id', models.IntegerField()),
                ('page_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('advocate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_views', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_views', to='core.efiling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_shared_view',
                'indexes': [models.Index(fields=['efiling', 'is_active'], name='courtroom_s_efiling_bfedb1_idx')],
                'unique_together': {('efiling', 'advocate_user')},
            },
        ),
    ]
