# Generated by Django 6.0.3 on 2026-03-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courtroomdocumentannotation',
            new_name='courtroom_d_judge_u_127da6_idx',
            old_name='courtroom_doc_anno_judge_idx',
        ),
        migrations.RenameIndex(
            model_name='courtroomforward',
            new_name='courtroom_f_forward_d181de_idx',
            old_name='courtroom_forward_fwd_date_bench_idx',
        ),
        migrations.RenameIndex(
            model_name='courtroomjudgedecision',
            new_name='courtroom_j_listing_a6e07d_idx',
            old_name='courtroom_judge_decision_list_date_approved_idx',
        ),
        migrations.RenameIndex(
            model_name='courtroomjudgedecision',
            new_name='courtroom_j_forward_c959f9_idx',
            old_name='courtroom_judge_decision_fwd_date_approved_idx',
        ),
    ]
