# Generated by Django 6.0.3 on 2026-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_rename_courtroom_doc_anno_judge_idx_courtroom_d_judge_u_127da6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtroomforward',
            name='listing_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
