# Generated by Django 6.0.3 on 2026-03-30 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('judge', '0003_courtroomforward_listing_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtroomForwardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling_document_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_requests', to='core.efilingdocumentsindex')),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_documents', to='judge.courtroomforward')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_forward_document',
                'indexes': [models.Index(fields=['forward'], name='courtroom_f_forward_f696cf_idx'), models.Index(fields=['efiling_document_index'], name='courtroom_f_efiling_3a90ea_idx')],
                'unique_together': {('forward', 'efiling_document_index')},
            },
        ),
    ]
