# Generated by Django 6.0.3 on 2026-03-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('judge', '0004_courtroomforwarddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtroomjudgedecision',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('REQUESTED_DOCS', 'Requested Documents')], default='DECLINED', max_length=20),
        ),
        migrations.CreateModel(
            name='CourtroomDecisionRequestedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling_document_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_requested_documents', to='core.efilingdocumentsindex')),
                ('judge_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_documents', to='judge.courtroomjudgedecision')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_decision_requested_document',
                'indexes': [models.Index(fields=['judge_decision'], name='courtroom_d_judge_d_d60af1_idx'), models.Index(fields=['efiling_document_index'], name='courtroom_d_efiling_a616a3_idx')],
                'unique_together': {('judge_decision', 'efiling_document_index')},
            },
        ),
    ]
