# Generated by Django 6.0.3 on 2026-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_courtroomjudgedecision_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtroomjudgedecision',
            name='listing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
