# Generated by Django 6.0.4 on 2026-04-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_judgestenomapping_judge_t'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='judgedraftannotation',
            new_name='judge_draft_workflo_b56c77_idx',
            old_name='judge_draft_workflo_346b69_idx',
        ),
        migrations.RenameIndex(
            model_name='judgedraftannotation',
            new_name='judge_draft_created_07ad80_idx',
            old_name='judge_draft_created_4284be_idx',
        ),
        migrations.RenameIndex(
            model_name='judgestenomapping',
            new_name='judge_steno_judge_i_01b793_idx',
            old_name='judge_steno_judge_i_7a1c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='judgestenomapping',
            new_name='judge_steno_steno_u_ff5b55_idx',
            old_name='judge_steno_steno_u_8e1451_idx',
        ),
        migrations.RenameIndex(
            model_name='judgestenomapping',
            new_name='judge_steno_bench_k_8ed9ee_idx',
            old_name='judge_steno_bench_k_4569d0_idx',
        ),
        migrations.RenameIndex(
            model_name='judgestenomapping',
            new_name='judge_steno_effecti_23c26c_idx',
            old_name='judge_steno_effecti_5194b9_idx',
        ),
    ]
