# Generated by Django 6.0.3 on 2026-03-31 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_alter_courtroomjudgedecision_listing_date'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courtroomforward',
            name='courtroom_f_forward_d181de_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courtroomforwarddocument',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='courtroomforwarddocument',
            name='courtroom_f_forward_f696cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='courtroomforwarddocument',
            name='courtroom_f_efiling_3a90ea_idx',
        ),
        migrations.RemoveField(
            model_name='courtroomforwarddocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='courtroomforwarddocument',
            name='efiling_document_index',
        ),
        migrations.RemoveField(
            model_name='courtroomforwarddocument',
            name='forward',
        ),
        migrations.RemoveField(
            model_name='courtroomforwarddocument',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='CourtroomForward',
        ),
        migrations.DeleteModel(
            name='CourtroomForwardDocument',
        ),
    ]
