# Generated by Django 6.0.3 on 2026-03-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0007_remove_courtroomforward_courtroom_f_forward_d181de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtroomjudgedecision',
            name='reader_listing_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
