# Generated by Django 6.0.3 on 2026-04-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_merge_0014_case_access_request_0014_purposet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note_content', models.TextField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_notes', to=settings.AUTH_USER_MODEL)),
                ('efiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_notes', to='core.efiling')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_office_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['efiling', '-created_at'], name='office_note_efiling_d749bf_idx')],
            },
        ),
    ]
