from .efiling_acts_views import EfilingActsListCreateView, EfilingActsRetrieveUpdateDestroyView
from .advocate_views import AdvocateListView, AdvocateRetrieveView
from .efiling_case_details_views import EfilingCaseDetailsListCreateView, EfilingCaseDetailsRetrieveUpdateDestroyView
from .efiling_litigant_views import EfilingLitigantListCreateView, EfilingLitigantRetrieveUpdateDestroyView
from .efiling_views import EfilingListCreateView, EfilingRetrieveUpdateDestroyView
from .ia_acts_views import IAActsListCreateView, IAActsRetrieveUpdateDestroyView
from .ia_views import IAListCreateView, IARetrieveUpdateDestroyView

