export const environment = {
  production: true,
  apiUrl: 'https://your-production-domain.com/api/v1',
  ssoConfig: {
    issuer: 'https://your-production-domain.com/o',
    redirectUri: window.location.origin + '/auth/callback',
    clientId: 'hcs-cms-frontend',
    responseType: 'code',
    scope: 'openid read write',
    useSilentRefresh: false,
    showDebugInformation: false,
    requireHttps: true,
    pkce: true,
    clearHashAfterLogin: false,
    tokenEndpoint: 'https://your-production-domain.com/o/token/',
    userinfoEndpoint: 'https://your-production-domain.com/o/userinfo/',
    logoutUrl: 'https://your-production-domain.com/o/revoke_token/',
    oidc: true,
  },
};
