export const docTypes = [
  {
    case_type_id: 4,
    code: "WP_C",
    documents: [
      "Index",
      "Synopsis",
      "List of Dates and Events",
      "Writ Petition",
      "Affidavit(s)",
      "Annexure(s)",
      "Vakalatnama",
      "Affidavit of Service",
      "Counter Affidavit with/without Annexure",
      "Rejoinders",
      "Additional Affidavits",
      "Compliance report",
      "Interlocutory Application",
      "Reply to Additional Affidavit/Interlocutory Application",
      "Compliance Affidavit",
      "Amended Writ Petition if directed by Court",
      "Better Affidavit",
    ],
  },
  {
    case_type_id: 26,
    code: "WP(PIL)",
    documents: [
      "Index",
      "Synopsis",
      "List of Dates and Events",
      "Writ Appeal",
      "Affidavit(s)",
      "Annexure(s)",
      "Vakalatnama",
      "Affidavit of Service",
      "Counter Affidavit with/without Annexure",
      "Rejoinder",
      "Additional Affidavits",
      "Compliance report / affidavit",
      "Interlocutory Application",
      "Reply to Additional Affidavit",
      "Compliance Affidavit",
      "Amendment in Writ Appeal if directed by Court",
      "Better Affidavit",
    ],
  },
  {
    case_type_id: 5,
    code: "ARB_A",
    documents: [
      "Index",
      "Synopsis",
      "List of Dates and Events",
      "Arbitration Appeal",
      "Affidavit(s) & Verification",
      "Annexure(s)",
      "Vakalatnama",
      "Affidavit of Service",
      "Compliance report / affidavit",
      "Interlocutory Application",
      "Reply to Interlocutory Application",
      "Better Affidavit",
    ],
  },
];
