# Generated by Django 6.0.3 on 2026-03-31 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtroomForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('forwarded_for_date', models.DateField()),
                ('bench_key', models.CharField(max_length=50)),
                ('listing_summary', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtroom_forwards', to='core.efiling')),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courtroom_forwards_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_forward',
            },
        ),
        migrations.CreateModel(
            name='CourtroomForwardDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('efiling_document_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_requests', to='core.efilingdocumentsindex')),
                ('forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_documents', to='reader.courtroomforward')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courtroom_forward_document',
            },
        ),
        migrations.AddIndex(
            model_name='courtroomforward',
            index=models.Index(fields=['forwarded_for_date', 'bench_key'], name='courtroom_f_forward_d181de_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomforwarddocument',
            index=models.Index(fields=['forward'], name='courtroom_f_forward_f696cf_idx'),
        ),
        migrations.AddIndex(
            model_name='courtroomforwarddocument',
            index=models.Index(fields=['efiling_document_index'], name='courtroom_f_efiling_3a90ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courtroomforwarddocument',
            unique_together={('forward', 'efiling_document_index')},
        ),
    ]
