# Generated by Django 6.0.4 on 2026-04-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_readerdailyproceeding_stenoorderworkflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='readerdailyproceeding',
            new_name='reader_dail_bench_k_0e416e_idx',
            old_name='reader_daily_bench_k_0f7c26_idx',
        ),
        migrations.RenameIndex(
            model_name='readerdailyproceeding',
            new_name='reader_dail_next_li_221a2c_idx',
            old_name='reader_daily_next_li_b55f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='stenoorderworkflow',
            new_name='steno_order_assigne_ec7641_idx',
            old_name='steno_order_assigne_44db2c_idx',
        ),
        migrations.RenameIndex(
            model_name='stenoorderworkflow',
            new_name='steno_order_judge_a_8a9f18_idx',
            old_name='steno_order_judge_a_3ff9a6_idx',
        ),
    ]
