# Generated by Django 6.0.4 on 2026-04-09 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_benchworkflowstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='benchworkflowstate',
            new_name='bench_workf_forward_2c4179_idx',
            old_name='bench_workf_forward_2c84aa_idx',
        ),
        migrations.RenameIndex(
            model_name='benchworkflowstate',
            new_name='bench_workf_is_publ_e9bc04_idx',
            old_name='bench_workf_is_publ_96e8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='benchworkflowstate',
            new_name='bench_workf_all_req_d609c1_idx',
            old_name='bench_workf_all_req_54d67e_idx',
        ),
        migrations.RenameIndex(
            model_name='benchworkflowstate',
            new_name='bench_workf_efiling_a2f8cb_idx',
            old_name='bench_workf_efiling_a78a6d_idx',
        ),
        migrations.AlterField(
            model_name='benchworkflowstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='benchworkflowstate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='benchworkflowstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='benchworkflowstate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
