# Generated by Django 6.0.3 on 2026-04-12 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_efiling_documents_index_scrutiny_columns_if_missing'),
        ('reader', '0006_rename_bench_workf_forward_2c84aa_idx_bench_workf_forward_2c4179_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtroomforward',
            name='bench_role_group',
            field=models.CharField(blank=True, default='', help_text='Reader slot on this bench (e.g. BENCH_S0). Unique per efiling/date/bench with listing flow.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='courtroomforward',
            index=models.Index(fields=['efiling', 'forwarded_for_date', 'bench_key', 'bench_role_group'], name='courtroom_f_efiling_4d6837_idx'),
        ),
        migrations.AddConstraint(
            model_name='courtroomforward',
            constraint=models.UniqueConstraint(fields=('efiling', 'forwarded_for_date', 'bench_key', 'bench_role_group'), name='courtroom_forward_efiling_date_bench_slot_uniq'),
        ),
    ]
