# Generated by Django 6.0.4 on 2026-04-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_courtroomforward_reader_slot_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courtroomforward',
            new_name='courtroom_f_forward_cf3819_idx',
            old_name='courtroom_f_forward_8a1b2c_idx',
        ),
    ]
