# Generated by Django 6.0.4 on 2026-04-17 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_readerdailyproceeding_steno_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stenoorderworkflow',
            name='workflow_status',
            field=models.CharField(choices=[('PENDING_UPLOAD', 'Pending Upload'), ('UPLOADED_BY_STENO', 'Uploaded by Steno'), ('SENT_FOR_JUDGE_APPROVAL', 'Sent for Judge Approval'), ('CHANGES_REQUESTED', 'Changes Requested'), ('JUDGE_APPROVED', 'Judge Approved'), ('SHARED_FOR_SIGNATURE', 'Shared For Signature'), ('SIGNATURES_IN_PROGRESS', 'Signatures In Progress'), ('SIGNED_AND_PUBLISHED', 'Signed and Published')], default='PENDING_UPLOAD', max_length=40),
        ),
        migrations.CreateModel(
            name='StenoWorkflowSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bench_role_group', models.CharField(blank=True, max_length=32, null=True)),
                ('signature_status', models.CharField(choices=[('PENDING', 'Pending'), ('SIGNED', 'Signed')], default='PENDING', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('judge_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steno_workflow_signatures', to=settings.AUTH_USER_MODEL)),
                ('steno_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steno_signature_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_rows', to='reader.stenoorderworkflow')),
            ],
            options={
                'db_table': 'steno_workflow_signature',
                'indexes': [models.Index(fields=['workflow', 'signature_status'], name='steno_workf_workflo_88738e_idx'), models.Index(fields=['steno_user'], name='steno_workf_steno_u_837896_idx')],
                'constraints': [models.UniqueConstraint(fields=('workflow', 'judge_user'), name='steno_workflow_signature_unique_workflow_judge')],
            },
        ),
    ]
