# Generated by Django 6.0.4 on 2026-04-18 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0015_merge_0011_reallocation_0014_steno_flow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='readercasereallocation',
            new_name='reader_case_efiling_f0c9ff_idx',
            old_name='reader_case__efiling_dfa191_idx',
        ),
        migrations.RenameIndex(
            model_name='readercasereallocation',
            new_name='reader_case_previou_de78e8_idx',
            old_name='reader_case__previou_63f2ec_idx',
        ),
        migrations.AlterField(
            model_name='readercasereallocation',
            name='reallocated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
